config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  get '/access', to: 'welcome#access', as: :access
  get '/hubs', to: 'welcome#hubs', as: :hubs
  get '/auth', to: 'welcome#auth', as: :auth
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base

  def index
    if params['code']
      session[:auth_code] = params['code']
    end
  end
  # {"access_token"=>"84AHoqLqZpEoRDSgIs15ypezXzmp", "refresh_token"=>"Rke4mOyTOn3ZLLroV1EtTLTJA88F2W2NsdlsxwfGMw", "token_type"=>"Bearer", "expires_in"=>86399}
  
  def access
    
    @result = HTTParty.post('https://developer.api.autodesk.com/authentication/v1/gettoken', 
    :body => { :client_id => 'XRj2rYsTCJOcbtRaW87AOY8GBjoyLGvS', 
               :client_secret => 'Jc599ef6bef864b4', 
               :grant_type => 'authorization_code', 
               :code => session[:auth_code], 
               :redirect_uri => 'http://localhost:3000'
             },
    :headers => { 'Content-Type' => 'application/x-www-form-urlencoded' } )
    session[:access_token] = @result["access_token"]
  end

  def hubs

    @result = HTTParty.get('https://developer.api.autodesk.com/project/v1/hubs',
      :headers => {'Authorization' => 'Bearer ' + session[:access_token]})
  end

  

  def auth
    # @result = HTTParty.post('https://developer.api.autodesk.com/authentication/v1/authenticate',
    #   :body => {:client_id => '11S6ResStiu0nWeVHRCf5RIJ5DIVnA9K',
    #             :client_secret => 'X2co5opbKfCSQff6',
    #             :grant_type => 'client_credentials',
    #             :scope => 'data:read data:write bucket:create bucket:read account:read user-profile:read'},
    #   :headers => {'Content-Type' => 'application/x-www-form-urlencoded'})

    # session[:token] = @result['access_token']

    #  @bucket = HTTParty.post('https://developer.api.autodesk.com/oss/v2/buckets',
    #   :headers => {'Authorization'=> 'Bearer ' + session[:token],
    #                'Content-Type'=> 'application/json'},
    #   :body => {'bucketKey' => 'mybucket1',
    #             'policyKey' => 'transient'}.to_json)

    #  @bucket = HTTParty.get('https://developer.api.autodesk.com/oss/v2/buckets/mybucket1/details',
    #             :headers => {'Authorization'=> 'Bearer ' + session[:token]})
    #  byebug
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestingForge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/access.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <h1><%= session[:access_token] %></h1>
  <%= link_to 'Get Hubs', hubs_path %>

</body>
</html>

app/views/welcome/auth.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <%= session[:token] %>
  <%= @hubs %>

</body>
</html>

app/views/welcome/hubs.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<h1><%= @result %></h1>

</body>
</html>

app/views/welcome/index.html.erb
<a href="https://developer.api.autodesk.com/authentication/v1/authorize?response_type=code&client_id=XRj2rYsTCJOcbtRaW87AOY8GBjoyLGvS&redirect_uri=http%3A%2F%2Flocalhost:3000&scope=data:read data:write bucket:create bucket:read account:read user-profile:read">Click here to grant access to your data!</a>
<% if session[:auth_code] %>
  <h3><%= session[:auth_code] %></h3>
  <p><%= link_to 'get refresh token', access_path %></p>
<% end %>